name: Deploy to Pawn

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Pawn
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PAWN_HOST }}
          username: ${{ secrets.PAWN_USER }}
          key: ${{ secrets.PAWN_SSH_KEY }}
          script: bash /root/acord-api/deploy.sh
